apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
    - name: event-payload
      description: Event payload
    - name: gitPlanningRepoUrl
      description: The planning repo where issue needs to be created.
    - name: gitToken
      description: git token
    - name: slackUrl
      description: the Slack Webhook Url
    - name: send-alert
      description: Specify if you want to send slack alert or not. Can be 0 or 1


  resourcetemplates:
    # CD secret to provide API_KEY to access toolchain information
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        gitToken: $(params.gitToken)
        slackUrl: $(params.slackUrl)
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: pipeline
        params:
          - name: event-payload
            value: $(params.event-payload)
          - name: pipeline-pvc
            value: pipelinerun-$(uid)-pvc
          - name: gitToken
            value: $(params.gitToken)
          - name: slackUrl
            value: $(params.slackUrl)
          - name: send-alert
            value: $(params.send-alert)
          
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding
spec:
  params:
      - name: event-payload
        value: $(body)
  

---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener
spec:
  triggers:
    - binding:
        name: trigger-binding
      template:
        name: trigger-template
